### ISSUE TITLE
HTML comparison issue

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-comparison/GroupDocs.Comparison-for-.NET-MVC#14]
When I do HTML comparison, I get following exception:
“Length cannot be less than zero.” and “Parameter name: length”.
Stack trace is:
" at System.String.Substring(Int32 startIndex, Int32 length)\r\n at \u000f​ .SaveImages(String \u0002)\r\n at \u000f​ .GetImages()\r\n at GroupDocs.Comparison.MVC.Products.Comparison.Service.ComparisonServiceImpl.GetCompareResultResponse(ICompareResult compareResult)

Can you please look into this issue?
Thanks 

This issue is raised in https://forum.groupdocs.com/t/added-html-as-allowed-file-type-in-net-comparison-mvc-and-get-error/6929

**Comment by Pavel-Teplitsky** [comment]
@atirtahirgroupdocs Thank you for reporting the issue. We have checked it and found out that the issue reason is in the GroupDocs.Comparison for .NET product. The issue will be fixed during this month. When it will be fixed We will notify you here.

Sorry for the inconvenience.

**Comment by Pavel-Teplitsky** [comment]
@atirtahirgroupdocs  this issue has been fixed. Please pull the latest changes for this repo and rebuild the solution.

**Comment by atirtahirgroupdocs** [comment]
@Pavel-Teplitsky Issue is resolved in latest version.
Thanks
