### ISSUE TITLE
Wrong Word comparison output 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-comparison/GroupDocs.Comparison-for-.NET-MVC#31]
This issue is raised in https://forum.groupdocs.com/t/groupdocs-comparison-for-net-mvc-example-problems/8273

Hi,
Please have a look at the attached videos and document with issue details below:
[files_2.zip](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-MVC/files/4548841/files_2.zip)
I am also uploading the problematic files:
[Problematic files.zip](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-MVC/files/4548844/Problematic.files.zip)
When I compare the attached Word files, output has changed position of the content. Have a look at the [wrong output.zip](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-MVC/files/4548850/wrong.output.zip).
However, I am not able to reproduce this issue in console application using API version 20.3.1.
Please take a look.
Thanks

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

This issue comes with oldest API version (19.6) which is used in this project.
We already working on API version update, so please stay tuned.

Regards

**Comment by kegor** [comment]
The issue is not longer reproducible on a current version of the Comparison sample app from the master-branch:

![image](https://user-images.githubusercontent.com/17431807/96180479-239e5c00-0f3b-11eb-8016-2c70889d86f1.png)
